### ISSUE TITLE
May you support Chrome?

### ISSUE THREAD

**Issue by nssurge** [deanishe/alfred-safari-assistant#10]
Thank you for your extraordinary work to create such a great Alfred Workflow. It's fantastic. I use Chrome at most time. And do you have any plan to support Chrome? Thanks anyway.

**Comment by deanishe** [comment]
No, not at this time.

That said, with the exception of a script or two, the workflow is mostly browser-agnostic.

All the Safari-specific stuff exists in [a separate library](https://github.com/deanishe/go-safari).

If someone rewrote that for Chrome, it would be relatively straightforward to port this workflow to Chrome.

**Comment by nssurge** [comment]
Ok. I know. Thanks anyway.
