### ISSUE TITLE
Add ability to search through specific folders 

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#11]
I would like to search through a specific folder in my bookmarks.

My use case is that I have few folders like `read` and `watch`:

![2018-07-21 at 21 43](https://user-images.githubusercontent.com/6391776/43039511-2dc9afe4-8d2f-11e8-8328-868a03ab6412.png)

And I want a hotkey I can press to filter only the folder I specify so I see this:

![2018-07-21 at 21 44](https://user-images.githubusercontent.com/6391776/43039517-3f68fbce-8d2f-11e8-9be2-8f52438b0b39.png)

But without Up to 'Favorites'. And activated from single hotkey. So I can pass in either name of folder or uid to this action and it filters the folder. 

Thank you.

**Comment by nikivdev** [comment]
By name of folder I was thinking of passing this `Favorites/read` to the action.

**Comment by nikivdev** [comment]
Although I just realized my entire workflow crumbles due to the fact that you can't delete bookmarks instantly with modifier presses due to #9.

I wrote an applescript to make GUI automated search on bookmarks folder but that's way too slow. This is sad.

**Comment by nikivdev** [comment]
I will close all the 3 issues I opened as #9 makes all of this not useful. I don't think anyone else uses bookmarks in this way.

**Comment by deanishe** [comment]
> And I want a hotkey I can press to filter only the folder I specify so I see this

That can easily be achieved by calling the `browse-folder` External Trigger with the appropriate variables.

The workflow helpfully dumps all the variables you need to the debugger.
