### ISSUE TITLE
Add ability to ignore folders in bookmarks search (bm)

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#12]
My use case is related to #11. Hopefully this workflow will support searching of specific folders.

With this, I would like to exclude some folders from my default `bm` search as I am using few folders as a `reading list` and thus don't want them to be part of bm search.

I can look into adding this feature myself, I believe Safari Go library will need to changed. 

I would really love it if you approved support for these two features. Thank you.

**Comment by nikivdev** [comment]
I think creating a variable like `IGNORE_FOLDERS` and passing in an array of folders to block: like `['Favorites/read', 'Favorites/watch', 'Favorites/check', 'Favorites/listen']` can work.

**Comment by deanishe** [comment]
> exclude some folders from my default bm search as I am using few folders as a reading list and thus don't want them to be part of bm search.

Well use Safari's proper Reading List instead. Those bookmarks aren't included in the `bm` search.

**Comment by nikivdev** [comment]
> Well use Safari's proper Reading List instead

You cant quickly remove things from Reading List either from Alfred.

Also Reading list is one huge list of things. I want some separation of concerts, i.e. video/read.

**Comment by nikivdev** [comment]
I moved back to [2Do](https://wiki.nikitavoloboev.xyz/other/2do-tasks.html) for this. Hopefully the dev will fix some issues I have with that approach and it would be okay to use.
