### ISSUE TITLE
Allow quickly closing tabs

### ISSUE THREAD

**Issue by MatanRubin** [deanishe/alfred-safari-assistant#17]
Thanks for the workflow, looks great.
Would it be possible to enhance the workflow to allow quickly closing tabs?
This would essentially mean that when the close tab action is used, the list stays open and the closed tab is removed from it.

This could be super useful when you have a million tabs open and you want to quickly go over them and close the ones you don't need anymore.

I'd be happy to help with this, given some guidance on how to do it.

**Comment by deanishe** [comment]
I don't understand what you mean. Have you assigned the "Close Tab" as an alternate action?

**Comment by MatanRubin** [comment]
Imagine I used the "tab" keyword to see the list of open tabs. Now imagine I want to go over the list and close 5 of the open tabs.

AFAIU, I would have to launch alfred 5 times using the tab keyword, because each time I close a tab, the tab list closes. If it were to remain open, I could continue going down the list and closing other tabs.

As I mentioned above, this is very useful when you have lots of open tabs and need a quick way to close some of them.

I hope this is clearer.

**Comment by deanishe** [comment]
So you *have* assigned "Close Tab" as an alternate action?

> If it were to remain open

Alfred doesn't really work that way. It's possible to leave the window open, but the workflow will be run again and the list of windows and tabs will be fetched from Safari again and re-displayed in Alfred.

More importantly, the workflow has no understanding of what the scripts it executes actually do, so it cannot know whether it's appropriate to re-open the tab (or bookmark) list after running a script or not. And in most cases, it isn't.

Any feature that relies on selecting multiple tabs/bookmarks/folders will have to wait until Alfred's file buffer supports arbitrary types (if it ever does).
