### ISSUE TITLE
Add iCloud tabs search to bmf search

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#2]
It would be quite awesome to have, and fits Safari Assistant theme too.

There is [this workflow](https://github.com/kmarchand/iCloudTabsAlfredWorkflow) but it doesn't work for me for some reason.

I mostly want to quickly search through tabs I have open on my iOS devices and ideally close them from the workflow (but read-only option would be good too).

Thank you.

**Comment by deanishe** [comment]
> it doesn't work for me for some reason.

It says it's Sierra and later only. You're not on Sierra yet, are you?

**Comment by nikivdev** [comment]
Yeah you are right. I can go to a previous commit of the workflow, there should be a version that would work on El Captain.
