### ISSUE TITLE
Add action to open all iCloud tabs in Safari and remove the tabs

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#20]
Very often I get lots of links open on my phone and I go to iCloud icon in Safari and cmd + click through all the open iCloud tabs and then close them:

![2018-10-23 at 09 43](https://user-images.githubusercontent.com/6391776/47344151-1a5dba00-d6a8-11e8-9519-943001aa0081.png)

It would be awesome to get an action that would do this for me automatically. Open all iCloud tabs in my mac browser for me to go through. And delete the tabs in iCloud too as they are now transferred. 

I have a feeling that you can't delete open iCloud tabs from code, I hope I am wrong. If you can't, an action to just open all the iCloud tabs in my browser would work good too. I can then delete the tabs manually in the cloud icon myself in Safari.

**Comment by nikivdev** [comment]
going to give this a go. As I want to add #16 too

**Comment by deanishe** [comment]
> I have a feeling that you can't delete open iCloud tabs from code

Your feeling is correct. You can't.
