### ISSUE TITLE
Search active tab, if not search bookmarks/recent history

### ISSUE THREAD

**Issue by sundarv85** [deanishe/alfred-safari-assistant#21]
Question:

I would like to open a tab if it already is open and if it is not open, then search bookmarks/history and open it. 

For this, I’m first using the `tab` keyword and if it is not resulting in any active tab, then I’m  searching using the `bh` keyword.

Is there already a combination available which will do this one after the other?

If not, would it be possible to introduce a new keyword to do this? Or any other way to accomplish this workflow.

**Comment by deanishe** [comment]
It's technically possible, but I'm not sure of the utility: If you select a bookmark or history entry and the URL is already open in a tab, Safari activates the tab and reloads the page.

The tab feature mostly exists as a hook for running scripts (Close Tabs to Right etc.).
