### ISSUE TITLE
custom browser

### ISSUE THREAD

**Issue by huangboju** [deanishe/alfred-safari-assistant#22]
My default browser is Chrome, but i want use **bmf** open in Safari

**Comment by deanishe** [comment]
I'm hesitant to offer a "custom browser" option, seeing as the workflow is 100% based around Safari.

But in that case, it would also make sense to enforce Safari by default, I guess.

**Comment by deanishe** [comment]
[v0.6.2](https://github.com/deanishe/alfred-safari-assistant/releases/tag/v0.6.2) explicitly opens URLs in Safari.
