### ISSUE TITLE
Add an option to copy URL of tab

### ISSUE THREAD

**Issue by karkraeg** [deanishe/alfred-safari-assistant#26]
Feature request: Add an option to copy URL of tab as plain text or as Markdown Link (to quickly cite an open tab while writing).

**Comment by deanishe** [comment]
Should be easy enough to implement with a script.

**Comment by karkraeg** [comment]
Great! Can I set this as `ALSF_TAB_SHIFT` so that I can access the copyed URL without going to `Other actions…` ?

**Comment by deanishe** [comment]
I haven’t tested that, but it should work: it’s just another tab script.
