### ISSUE TITLE
Modifier keys don't work with History and Bookmarks + History items

### ISSUE THREAD

**Issue by andreiborisov** [deanishe/alfred-safari-assistant#27]
For some reason, I cannot use modifier keys with search results from `bh` and `hi`, while on `bm` and `rl` they are properly showing up. It's important to note, that using `Command` modifier key to go to "Other actions..." list works as expected in all cases.

**Comment by deanishe** [comment]
Thanks for finding this. Fixed in [v0.7.1](https://github.com/deanishe/alfred-safari-assistant/releases/tag/v0.7.1).
