### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by haakonstorm** [deanishe/alfred-safari-assistant#28]
* Latest macos, alfred and plugin.
* alfred preferences in a Dropbox folder, set up via Alfred prefs

Starting debug for 'Safari Assistant'

[2019-04-08 13:56:42][ERROR: input.scriptfilter] Code 1: 13:56:42 workflow_paths.go:156: [warning] info.plist not found. Guessed workflow directory: /Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7
🍺
13:56:42 workflow.go:300: ------ Safari Assistant/0.7.1 (AwGo/0.15.0) ------
13:56:42 actions.go:342: Tab Script "Copy URL as Markdown" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/tab/Copy URL as Markdown.js"
13:56:42 actions.go:342: Tab Script "Copy URL" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/tab/Copy URL.js"
13:56:42 actions.go:342: Tab Script "Reopen in New Window" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/tab/Reopen in New Window.js"
13:56:42 actions.go:352: URL Script "Open in Chrome" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in Chrome.sh"
13:56:42 actions.go:352: URL Script "Open in Current Tab" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in Current Tab.js"
13:56:42 actions.go:352: URL Script "Open in Firefox" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in Firefox.sh"
13:56:42 actions.go:352: URL Script "Open in New Safari Window" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in New Safari Window.js"
13:56:42 actions.go:352: URL Script "Open in Private Window" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in Private Window.js"
13:56:42 actions.go:352: URL Script "Open in Safari" from "/Users/hsh/Dropbox/Databaser/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F8227BDE-4AE2-4048-AA82-2230816E9AB7/scripts/url/Open in Safari.sh"
13:56:42 feedback.go:447: Sent 1 result(s) to Alfred
13:56:42 workflow.go:348: [ERROR] load scripts: lstat /Users/hsh/Library/Application Support/Alfred 3/Workflow Data/net.deanishe.alfred.safari/scripts/tab: no such file or directory
13:56:42 workflow.go:351: Get help at https://github.com/deanishe/alfred-safari-assistant/issues
13:56:42 workflow.go:376: ------------------- 14.79376ms -------------------

**Comment by deanishe** [comment]
Shit! I [fixed this regression yesterday](https://github.com/deanishe/alfred-safari-assistant/commit/0bd617ae16d34a309fe154e8bd3a3b47c6e413ed#diff-e42ddc93aac5d446e3455d8666d3c94dR324) but I haven't released a new version yet 🙁  

For the time being, you could create the missing directories with the following command:

```
mkdir -p /Users/hsh/Library/Application\ Support/Alfred\ 3/Workflow\ Data/net.deanishe.alfred.safari/scripts/{tab,url}
```

**Comment by nikivdev** [comment]
Just updated to the latest version and get 

![2019-04-09 at 18 01](https://user-images.githubusercontent.com/6391776/55815977-97afa680-5af1-11e9-908d-d80eacd298f2.png)

On version 3.8.1 which Alfred says is the latest.

![2019-04-09 at 18 02](https://user-images.githubusercontent.com/6391776/55815995-9ed6b480-5af1-11e9-9796-a508473e21c5.png)

**Comment by deanishe** [comment]
It seems to have been a bad build. [Can you re-download the workflow file](https://github.com/deanishe/alfred-safari-assistant/releases/download/v0.7.2/Safari-Assistant-0.7.2.alfredworkflow) and re-install?

**Comment by nikivdev** [comment]
works now. Thanks

**Comment by haakonstorm** [comment]
Excellent workflow! Thank you! Why didn't I find this years ago? :D
/Storm

**Comment by nikivdev** [comment]
> Why didn't I find this years ago?

There's a few more workflows that are pretty cool [here](https://github.com/learn-anything/alfred-workflows#readme) you may like 🙂.
