### ISSUE TITLE
Alfred4 not working

### ISSUE THREAD

**Issue by huangboju** [deanishe/alfred-safari-assistant#30]

**Comment by deanishe** [comment]
Alfred 4 support was added in [v0.7.2](https://github.com/deanishe/alfred-safari-assistant/releases/tag/v0.7.2). It works fine for me.

If you can't provide a better description of your problem (the debugger output at least), I can't help you.

**Comment by huangboju** [comment]
![image](https://user-images.githubusercontent.com/14818224/58690470-2935e900-83bc-11e9-9dbd-422e129bcc0f.png)
@deanishe

**Comment by huangboju** [comment]
I solved it
![image](https://user-images.githubusercontent.com/14818224/58690653-ac573f00-83bc-11e9-96b3-b4b40ec5144b.png)

**Comment by deanishe** [comment]
https://github.com/deanishe/alfred-safari-assistant#macos-mojave
