### ISSUE TITLE
Suggestion: Add option to use Safari Technology Preview

### ISSUE THREAD

**Issue by tinkertrain** [deanishe/alfred-safari-assistant#4]
Hi, thank you for the work you have put into Safari Assistant.

I was wondering if it's possible to add a configuration option to use Safari Technology Preview in place of regular Safari?

Or, if this not in the scope of this project, can you point me in the direction of where can I replace it in the source files so I can build it myself?

Thanks again

**Comment by deanishe** [comment]
> can you point me in the direction of where can I replace it in the source files so I can build it myself?

Most of the Safari stuff is in [a separate library](https://github.com/deanishe/go-safari).

You'd need to make a new version of that library with the path to the bookmarks file changed & all of the JavaScript scripts updated to call the different application name.

Then you need to change this workflow to use your new library, and also update the JavaScript scripts in this workflow, too.

There might be other things, too.

**Comment by tinkertrain** [comment]
I see, I think I might skip this for now as I don't know go. Thanks for the reply though!

J⋃ɑɴ Рαʙʟο ᏞοⅿеʟᎥ DᎥɑz
@tinkertrain
