### ISSUE TITLE
Bug: Mac 10.15

### ISSUE THREAD

**Issue by huangboju** [deanishe/alfred-safari-assistant#44]
I upgraded to 10.15, it is not working

![image](https://user-images.githubusercontent.com/14818224/67258869-41221c80-f4c5-11e9-99ff-e79e29f23663.png)

**Comment by huangboju** [comment]
I reinstall it, it is working

**Comment by deanishe** [comment]
Apparently, Catalina is so stupid, it deletes the workflow executable: deanishe/alfred-sublime-text#20
