### ISSUE TITLE
Add ability to view recently closed tabs

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#5]
[Recent Tab List](http://nickvdp.com/tablist/) has an awesome feature that lets you see recently closed tabs in Safari.

It would be awesome to view a list of 10/20 recently closed tabs in Safari in Alfred.

**Comment by deanishe** [comment]
And where is the list of recently-closed tabs stored?

**Comment by nikivdev** [comment]
Never mind, the [extension tracks each closed tab](https://github.com/nickvdp/RecentTabList/blob/master/RecentTabList.safariextension/recentTabList.js#L7) internally.
