### ISSUE TITLE
Open browse-folder with specific folder pre-selected

### ISSUE THREAD

**Issue by dvcrn** [deanishe/alfred-safari-assistant#6]
Fantastic workflow! Great job :) 

I am trying to expand it with a custom hotkey to browse all bookmarks in a specific folder. Looking at the workflow, I should be able to just use the `browse-folder` target with applescript, but I can't figure out what ID I have to pass. 

I enabled debug, executed the workflow and tried using the ALSF_UID variable, but that doesn't seem to be the one. 

```
    "ALSF_UID" = "4BA98C7D-7F06-432E-BD0A-474FFB945059";
```

**Comment by deanishe** [comment]
> tried using the ALSF_UID variable

How are you setting the variable?

**Comment by dvcrn** [comment]
Oh that might have been my problem. I invoked it with the applescript suggested by alfred and simply passed the id as argument

```
tell application "Alfred 3" to run trigger "browse-folder" in workflow "net.deanishe.alfred.safari" with argument "4BA98C7D-7F06-432E-BD0A-474FFB945059"
```

Is there a correct way of doing this?

**Comment by deanishe** [comment]
> `with argument`

That sets the query, not variables. You want to call it without an argument. AFAIK, there's no way to set a variable via AppleScript.

You'll need to add an Args & Vars utility to set `ALSF_UID`.

Also, keep an eye on the debugger. The input query and variables to each element are dumped in the debugger.

**Comment by dvcrn** [comment]
Thanks, I got it working with a `Call external` from a different workflow. Interesting, I didn't know Alfred can do this 😄 

![screen shot 2018-05-20 at 15 27 10](https://user-images.githubusercontent.com/688326/40276334-5ad7aa9a-5c42-11e8-98ef-4ff91fdaae8b.png)

Thanks for the help
