### ISSUE TITLE
Add ability to change what `CMD+RETURN` does

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#7]
I would like to reconfigure default action for `Show actions for selected item` from `⌘↩` to `⌥↩`  or any other key.

Currently I can't do that. In my case I wanted to set `ALSF_URL_CMD` option to `Open in Chrome` as I use that action many more times than `Show actions for selected item`.

**Comment by deanishe** [comment]
> as I use that action many more times than Show actions for selected item

Why can't you press `⌥↩` instead? `⌥` isn't very far from `⌘`…

**Comment by nikivdev** [comment]
> Why can't you press ⌥↩ instead? ⌥ isn't very far from ⌘…

On my system cmd + return is `f + l` and opt + return is `f + m`. The main reason for this change is that I nearly never want to use `More options` modifier as I bind all the things I need directly to modifiers but cmd + return is usually my most used modifier.

If this change is hard to make, it's not worth making it of course. Just would be nice for me, I doubt any one else cares about this.

In fact in my version of the workflow `More Options` wouldn't exist. I would just bind everything to modifiers. The 5 modifiers are enough to do all the actions I need.

**Comment by deanishe** [comment]
Like I've told you before: if the only reason you have for submitting a change request is to suit your extremely unusual workflow, I'm not interested.

Especially when you're asking me to change the way the workflow works for *everyone*.

> In fact in my version of the workflow More Options wouldn't exist.

Then fork the repo and build your version…

I'll leave the issue open for a few days in case anyone else has a better reason for the proposed change.
