### ISSUE TITLE
Allow to open 'invalid' URLs

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#8]
I have these 3 bookmarks saved in Safari: 
- `chrome://extensions/` 
- `chrome://flags/`
- `chrome://extensions/configureCommands`

![2018-05-28 at 16 15](https://user-images.githubusercontent.com/6391776/40618615-5891977c-6292-11e8-9238-00c9b793a3ef.png)

I saved them in Safari and tried to open them in Chrome but nothing happened. I assume its because those three URLs are URL schemes.

It would be nice to let users open them. Thank you.

**Comment by deanishe** [comment]
```
❯ open chrome://extensions
The file ~/Desktop/chrome:/extensions does not exist.
in ~/Desktop
✖ 1 ❯ open -a 'Google Chrome' chrome://extensions
The file ~/Desktop/chrome:/extensions does not exist.
in ~/Desktop
✖ 1 ❯
```
The system does not understand the URL scheme (so the workflow doesn't either). Safari certainly doesn't. It only works in Chrome's own address bar.

That is why such URLs (along with Safari's own `favorites://` and `bookmarks://`) are ignored.
