### ISSUE TITLE
Any chance of adding delete function

### ISSUE THREAD

**Issue by hugh1li** [deanishe/alfred-safari-assistant#9]
Awesome workflow. But sometimes I wanna delete a safari (or chrome) bookmark using alfred. Any possibility?

**Comment by deanishe** [comment]
Nope, no chance I'm afraid. Safari's bookmarks, reading list and history are strictly read-only.

AFAIK, there is no (external) API for editing Safari's bookmarks.

**Comment by nikivdev** [comment]
Is there no way you can ammend the read-only bookmarks? Safari can delete the bookmarks from its GUI bookmark manager, perhaps it deletes them by their uid if they have one. Maybe Safari 12.0 changed something.

**Comment by deanishe** [comment]
> Is there no way you can ammend the read-only bookmarks?

No. There is no bookmarks API.

> Maybe Safari 12.0 changed something.

Why don't you try to find out yourself before asking me?

**Comment by nikivdev** [comment]
> Why don't you try to find out yourself before asking me?

It was just a note. I can't upgrade to Mojawe yet but will do soon and will certainly try. Deleting bookmarks quickly is still an annoying issue.

**Comment by deanishe** [comment]
> Deleting bookmarks quickly is still an annoying issue.

Yes, it is. And as explained when I closed the issue, this workflow does not (and never will) alter Safari's private data.

I suggest you look into Safari Extensions, which do have the ability to manipulate Safari's bookmarks.
